### ISSUE TITLE
Use of 'name'

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_Hebrew#5]
From our discussion at ACL, it sounded like the treebanks converted to UD lacked named entity annotations, and thus there was no simple way to produce `name` relations. However, there are [plenty of `name` relations](http://bionlp-www.utu.fi/dep_search/?db=Hebrew&search=_+%3Cname+_) in the data. Why is this?

**Comment by dan-zeman** [comment]
The `name` relation should not be understood as a replacement for named entity annotation (which really is not covered by UD at the moment). I see it rather as a back-off solution for cases where no normal (syntactic) relations are suitable, most notably between a first name and a last name of a person.

**Comment by yoavg** [comment]
@nschneid this was due to a mistake on my part when we met. I forgot that we did use `name` for chains of proper nouns, as @dan-zeman also suggests in the message above me.
