### ISSUE TITLE
Relabel 'nmod:smixut' as 'compound'?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_Hebrew#6]
In my view, the smixut construction has elements of both genitive-ness and compound-ness. Perhaps instead of a language-specific label `nmod:smixut`, a cleaner solution would be to use `compound`, which is supposedly universal but currently unused in Hebrew.

**Comment by amir-zeldes** [comment]
I agree and think this is most consistent with a view like Borer (2008), especially if it's desirable to avoid questions of transparent vs. opaque smixut. I think from a syntactic point of view, the absence of article capability on both lexemes at once points to a single nominal kernel (like Germanic or Romance compounds), and morphologically, the mutation of the smixut head is a sign of lexical integration, like in Germanic compound stem forms. Compare:

```
Das Krankenhaus 'the sick+LINK+house' = hospital
* Die Kranken das Haus 'the sick-the house'
beit ha-xolim 'house_LINK the sick' = hospital
* ha-bait ha-xolim 'the house the sick'
```

The change from 'bait' outside compounds to 'beit' in compounds mirrors similar processes in German (e.g. a stem like Haus going to Häus) - a syntactic genitive offers no motivation for the morphological change of what in Hebrew is supposed to be the governing, not governed unit. A syntactic genitive would also lead us to expect that either or both of the two NPs can be made definite, but this is not the case.

For these reasons, I'm all for compound, and if there is a need to delineate other types of compounds in Hebrew (which are very rare), then I think compound:smixut is also an option.

**Comment by amir-zeldes** [comment]
Reference:
Borer, H. 2008. Compounds: The View from Hebrew. In Lieber, R./Štekauer, P. (eds.) The Oxford Handbook of Compounds. Oxford: Oxford University Press, 491–511.

**Comment by nschneid** [comment]
> A syntactic genitive would also lead us to expect that either or both of the two NPs can be made definite, but this is not the case.

Not sure I understand this argument about making both NPs definite. Why doesn't this rule out the English _'s_ genitive: _the boy's cookie_, _*the boy's the cookie_?

**Comment by amir-zeldes** [comment]
Yes, that's true, the English genitive 's is a bit different than what I had in mind. TBH I was thinking more of German compounds, which are very different from the German genitive, which allows two articles post-nominally:

Ein Freund meines Sohnes 
'a.nom friend.nom my.gen son.gen'

Either determiner can be definite or indefinite for all possible combinations, whereas in a compound only one article is possible and it applies to the entire compound, just like in smixut.

I think it's not as easy to tell, but in English there is a subtle ambiguity that can be read into 'the boy's cookie', which is similar: if there is a specific, definite boy, we get the usual reading, and we could say the article applies to the boy. But there is also an odd reading, in which there is no specific boy, but there is a type of cookie associated with boys, which is a 'boy cookie', and this is a specific exemplar of such a cookie (the article applies to 'cookie'). 

This latter case is a lot like a compound with a single article. In the normal reading of 'the boy's cookie', my intuition is that the article belongs to the modifier, and is thus different from the smixut case. The definiteness of the entire cookie is a sort of by-product of being possessed by a definite entity (much like 'his cookie' works as a definite determiner in English, but compare Italian: il mio amico 'my friend' vs. un mio amico 'a friend of mine')

**Comment by nschneid** [comment]
> But there is also an odd reading, in which there is no specific boy, but there is a type of cookie associated with boys, which is a 'boy cookie', and this is a specific exemplar of such a cookie (the article applies to 'cookie'). 

A more ambiguous example would be "the boys' choir". It could be a specific instance of a kind of choir consisting of boys; or it could be the choir that certain boys belong to.

**Comment by habeanf** [comment]
nmod:smixut was changed in udv2 to compound:smixut . Can we close this issue?

**Comment by habeanf** [comment]
Discussed with @rtsarfaty offline. Closing since we've made the change to compound:smixut in v2
