### ISSUE TITLE
Some universal relations do not appear

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_Hebrew#7]
The following supposedly universal relations do not appear in the Hebrew data:
- `compound` (see #5)
- `discourse` (but there is `conj:discourse`)
- `expl`
- `foreign`
- `list`
- `remnant`
- `reparandum`
- `vocative`

Is this because no relevant examples happen to appear in the data? Are there no good heuristics to detect them from the source treebanks? Or are these relations excluded on purpose?

**Comment by yoavg** [comment]
- `compound` may be added when we resolve #6 
-  It is not clear to me from the documentation what `discourse` stands for, but I am pretty sure it is different from our use of `conj:discourse`
- `expl` I do not think we have these in the data. Perhaps יש and אין can be treated this way, but we are already discussing those.. #8 
- `foreign`, `list` we have no good way of identifying these
- `remnant` initially we left out as hard to identify, now I'd wait for the decision on replacement for v2
- `reparandum` I am pretty sure the data does not have these (or maybe just one or two examples)
- `vocative` there is no reliable way to identify, but we admittedly did not try very hard

**Comment by nschneid** [comment]
> - It is not clear to me from the documentation what `discourse` stands for, but I am pretty sure it is different from our use of `conj:discourse`

I think you're right. At least in English, `discourse` is used for "please", "yes"/"no", interjections, and emoticons. I see 3 tokens tagged as `INTJ` in the Hebrew corpus—should these be linked with `discourse`? Currently, 2 of them are `advmod` and one is `dep`.
