### ISSUE TITLE
Shouldn't אם be SCONJ instead of CONJ?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_Hebrew#9]
I was surprised to see that אם is labeled `CONJ` in the Hebrew data though "if" is [`SCONJ`](http://universaldependencies.org/u/pos/SCONJ.html) in English. Is there a linguistic rationale?

**Comment by yoavg** [comment]
It's a leftover from previous versions of the treebank. I will fix this and push soon.

**Comment by yoavg** [comment]
Fixed.
